### ISSUE TITLE
UTF8 by default

### ISSUE THREAD

**Issue by stefan-balke** [ismir/paper_templates#15]
Hi,

I noticed that UTF-8 is not set by default.
However, putting `\usepackage[utf8]{inputenc}` in the template should not hurt.
This will prevent people from having issues with special characters such as ä, ü, ö...

Should be added in ISMIR 19's template and the TISMIR template.

**Comment by f0k** [comment]
In addition, you should put `\usepackage[T1]{fontenc}`! Otherwise you cannot properly copy/paste Umlauts from the text. These are the two I have to add to almost every paper template, not only ISMIR. Wouldn't hurt to put them in by default, maybe with a comment on what they do.

**Comment by stefan-balke** [comment]
resolved in #17
